package es.upv.grycap.tracer.model.trace;

public enum TraceReqCacheStatus {
	RECEIVED_OK, PARSING, PARSED_OK, PARSING_ERROR, CACHING, CACHED_OK, CACHING_ERROR, STORING_BLOCKCHAIN, BLOCKCHAIN_STORED_OK, BLOCKCHAIN_STORED_ERROR
}
